import requests
from bs4 import BeautifulSoup

# List of URLs to scrape
urls = [
'https://api.mojang.com/users/profiles/minecraft/adjustable ',
'https://api.mojang.com/users/profiles/minecraft/adjusted ',
'https://api.mojang.com/users/profiles/minecraft/adjustment ',
'https://api.mojang.com/users/profiles/minecraft/adjustments ',
'https://api.mojang.com/users/profiles/minecraft/admin ',
'https://api.mojang.com/users/profiles/minecraft/administered ',
'https://api.mojang.com/users/profiles/minecraft/administration ',
'https://api.mojang.com/users/profiles/minecraft/administrative ',
'https://api.mojang.com/users/profiles/minecraft/administrator ',
'https://api.mojang.com/users/profiles/minecraft/administrators ',
'https://api.mojang.com/users/profiles/minecraft/admission ',
'https://api.mojang.com/users/profiles/minecraft/admissions ',
'https://api.mojang.com/users/profiles/minecraft/admit ',
'https://api.mojang.com/users/profiles/minecraft/admitted ',
'https://api.mojang.com/users/profiles/minecraft/adobe ',
'https://api.mojang.com/users/profiles/minecraft/adolescent ',
'https://api.mojang.com/users/profiles/minecraft/adopt ',
'https://api.mojang.com/users/profiles/minecraft/adopted ',
'https://api.mojang.com/users/profiles/minecraft/adoption ',
'https://api.mojang.com/users/profiles/minecraft/adrian ',
'https://api.mojang.com/users/profiles/minecraft/ads ',
'https://api.mojang.com/users/profiles/minecraft/adsl ',
'https://api.mojang.com/users/profiles/minecraft/adult ',
'https://api.mojang.com/users/profiles/minecraft/adults ',
'https://api.mojang.com/users/profiles/minecraft/amazoncouk ',
'https://api.mojang.com/users/profiles/minecraft/ambassador ',
'https://api.mojang.com/users/profiles/minecraft/amber ',
'https://api.mojang.com/users/profiles/minecraft/ambien ',
'https://api.mojang.com/users/profiles/minecraft/ambient ',
'https://api.mojang.com/users/profiles/minecraft/amd ',
'https://api.mojang.com/users/profiles/minecraft/amend ',
'https://api.mojang.com/users/profiles/minecraft/amended ',
'https://api.mojang.com/users/profiles/minecraft/amendment ',
'https://api.mojang.com/users/profiles/minecraft/amendments ',
'https://api.mojang.com/users/profiles/minecraft/amenities ',
'https://api.mojang.com/users/profiles/minecraft/america ',
'https://api.mojang.com/users/profiles/minecraft/american ',
'https://api.mojang.com/users/profiles/minecraft/americans ',
'https://api.mojang.com/users/profiles/minecraft/americas ',
'https://api.mojang.com/users/profiles/minecraft/amino ',
'https://api.mojang.com/users/profiles/minecraft/among ',
'https://api.mojang.com/users/profiles/minecraft/amongst ',
'https://api.mojang.com/users/profiles/minecraft/amount ',
'https://api.mojang.com/users/profiles/minecraft/amounts ',
'https://api.mojang.com/users/profiles/minecraft/amp ',
'https://api.mojang.com/users/profiles/minecraft/ampland ',
'https://api.mojang.com/users/profiles/minecraft/amplifier ',
'https://api.mojang.com/users/profiles/minecraft/amsterdam ',
'https://api.mojang.com/users/profiles/minecraft/amy ',
'https://api.mojang.com/users/profiles/minecraft/an ',
'https://api.mojang.com/users/profiles/minecraft/ana ',
'https://api.mojang.com/users/profiles/minecraft/anaheim ',
'https://api.mojang.com/users/profiles/minecraft/anal ',
'https://api.mojang.com/users/profiles/minecraft/analog ',
'https://api.mojang.com/users/profiles/minecraft/analyses ',
'https://api.mojang.com/users/profiles/minecraft/analysis ',
'https://api.mojang.com/users/profiles/minecraft/analyst ',
'https://api.mojang.com/users/profiles/minecraft/analysts ',
'https://api.mojang.com/users/profiles/minecraft/analytical ',
'https://api.mojang.com/users/profiles/minecraft/analyze ',
'https://api.mojang.com/users/profiles/minecraft/analyzed ',
'https://api.mojang.com/users/profiles/minecraft/anatomy ',
'https://api.mojang.com/users/profiles/minecraft/anchor ',
'https://api.mojang.com/users/profiles/minecraft/ancient ',
'https://api.mojang.com/users/profiles/minecraft/and ',
'https://api.mojang.com/users/profiles/minecraft/andale ',
'https://api.mojang.com/users/profiles/minecraft/anderson ',
'https://api.mojang.com/users/profiles/minecraft/andorra ',
'https://api.mojang.com/users/profiles/minecraft/andrea ',
'https://api.mojang.com/users/profiles/minecraft/andreas ',
'https://api.mojang.com/users/profiles/minecraft/andrew ',
'https://api.mojang.com/users/profiles/minecraft/andrews ',
'https://api.mojang.com/users/profiles/minecraft/andy ',
'https://api.mojang.com/users/profiles/minecraft/angel ',
'https://api.mojang.com/users/profiles/minecraft/angela ',
'https://api.mojang.com/users/profiles/minecraft/angeles ',
'https://api.mojang.com/users/profiles/minecraft/angels ',
'https://api.mojang.com/users/profiles/minecraft/anger ',
'https://api.mojang.com/users/profiles/minecraft/angle ',
'https://api.mojang.com/users/profiles/minecraft/angola ',
'https://api.mojang.com/users/profiles/minecraft/angry ',
'https://api.mojang.com/users/profiles/minecraft/animal ',
'https://api.mojang.com/users/profiles/minecraft/animals ',
'https://api.mojang.com/users/profiles/minecraft/animated ',
'https://api.mojang.com/users/profiles/minecraft/animation ',
'https://api.mojang.com/users/profiles/minecraft/anime ',
'https://api.mojang.com/users/profiles/minecraft/ann ',
'https://api.mojang.com/users/profiles/minecraft/anna ',
'https://api.mojang.com/users/profiles/minecraft/anne ',
'https://api.mojang.com/users/profiles/minecraft/annex ',
'https://api.mojang.com/users/profiles/minecraft/annie ',
'https://api.mojang.com/users/profiles/minecraft/anniversary ',
'https://api.mojang.com/users/profiles/minecraft/annotated ',
'https://api.mojang.com/users/profiles/minecraft/annotation ',
'https://api.mojang.com/users/profiles/minecraft/announce ',
'https://api.mojang.com/users/profiles/minecraft/announced ',
'https://api.mojang.com/users/profiles/minecraft/announcement ',
'https://api.mojang.com/users/profiles/minecraft/announcements ',
'https://api.mojang.com/users/profiles/minecraft/announces ',
'https://api.mojang.com/users/profiles/minecraft/annoying ',
'https://api.mojang.com/users/profiles/minecraft/annual ',
'https://api.mojang.com/users/profiles/minecraft/annually ',
'https://api.mojang.com/users/profiles/minecraft/anonymous ',
'https://api.mojang.com/users/profiles/minecraft/another ',
'https://api.mojang.com/users/profiles/minecraft/answer ',
'https://api.mojang.com/users/profiles/minecraft/answered ',
'https://api.mojang.com/users/profiles/minecraft/answering ',
'https://api.mojang.com/users/profiles/minecraft/answers ',
'https://api.mojang.com/users/profiles/minecraft/ant ',
'https://api.mojang.com/users/profiles/minecraft/antarctica ',
'https://api.mojang.com/users/profiles/minecraft/antenna ',
'https://api.mojang.com/users/profiles/minecraft/anthony ',
'https://api.mojang.com/users/profiles/minecraft/anthropology ',
'https://api.mojang.com/users/profiles/minecraft/anti ',
'https://api.mojang.com/users/profiles/minecraft/antibodies ',
'https://api.mojang.com/users/profiles/minecraft/antibody ',
'https://api.mojang.com/users/profiles/minecraft/anticipated ',
'https://api.mojang.com/users/profiles/minecraft/antigua ',
'https://api.mojang.com/users/profiles/minecraft/antique ',
'https://api.mojang.com/users/profiles/minecraft/antiques ',
'https://api.mojang.com/users/profiles/minecraft/antivirus ',
'https://api.mojang.com/users/profiles/minecraft/antonio ',
'https://api.mojang.com/users/profiles/minecraft/anxiety ',
'https://api.mojang.com/users/profiles/minecraft/any ',
'https://api.mojang.com/users/profiles/minecraft/anybody ',
'https://api.mojang.com/users/profiles/minecraft/anymore ',
'https://api.mojang.com/users/profiles/minecraft/anyone ',
'https://api.mojang.com/users/profiles/minecraft/anything ',
'https://api.mojang.com/users/profiles/minecraft/anytime ',
'https://api.mojang.com/users/profiles/minecraft/anyway ',
'https://api.mojang.com/users/profiles/minecraft/anywhere ',
'https://api.mojang.com/users/profiles/minecraft/aol ',
'https://api.mojang.com/users/profiles/minecraft/ap ',
'https://api.mojang.com/users/profiles/minecraft/apache ',
'https://api.mojang.com/users/profiles/minecraft/apart ',
'https://api.mojang.com/users/profiles/minecraft/apartment ',
'https://api.mojang.com/users/profiles/minecraft/apartments ',
'https://api.mojang.com/users/profiles/minecraft/api ',
'https://api.mojang.com/users/profiles/minecraft/apnic ',
'https://api.mojang.com/users/profiles/minecraft/apollo ',
'https://api.mojang.com/users/profiles/minecraft/app ',
'https://api.mojang.com/users/profiles/minecraft/apparatus ',
'https://api.mojang.com/users/profiles/minecraft/apparel ',
'https://api.mojang.com/users/profiles/minecraft/apparent ',
'https://api.mojang.com/users/profiles/minecraft/apparently ',
'https://api.mojang.com/users/profiles/minecraft/appeal ',
'https://api.mojang.com/users/profiles/minecraft/appeals ',
'https://api.mojang.com/users/profiles/minecraft/appear ',
'https://api.mojang.com/users/profiles/minecraft/appearance ',
'https://api.mojang.com/users/profiles/minecraft/appeared ',
'https://api.mojang.com/users/profiles/minecraft/appearing ',
'https://api.mojang.com/users/profiles/minecraft/appears ',
'https://api.mojang.com/users/profiles/minecraft/appendix ',
'https://api.mojang.com/users/profiles/minecraft/apple ',
'https://api.mojang.com/users/profiles/minecraft/appliance ',
'https://api.mojang.com/users/profiles/minecraft/appliances ',
'https://api.mojang.com/users/profiles/minecraft/applicable ',
'https://api.mojang.com/users/profiles/minecraft/applicant ',
'https://api.mojang.com/users/profiles/minecraft/applicants ',
'https://api.mojang.com/users/profiles/minecraft/application ',
'https://api.mojang.com/users/profiles/minecraft/applications ',
'https://api.mojang.com/users/profiles/minecraft/applied ',
'https://api.mojang.com/users/profiles/minecraft/applies ',
]

for url in urls:
    response = requests.get(url)

    if response.status_code == 200:
        page_content = response.content
    else:
        print(f"Failed to retrieve the webpage at {url}. Status code:", response.status_code)
        continue

    # Parse the HTML content with BeautifulSoup
    soup = BeautifulSoup(page_content, "lxml")

    # Find and retrieve the <body> tag
    body_tag = soup.find("body")

    if body_tag:
        # Get the HTML content of the <body> tag, including its contents
        body_content = str(body_tag)
        print(f"Body content for {url}:\n{body_content}\n")
    else:
        print(f"No <body> tag found on the page {url}.\n")
